volumes:
  db_volume:

services:



  db:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=local_rag_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=local_rag_db
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./config/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432