services:

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=local_rag
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432