volumes:
  db_volume:

services:



  db:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=local_rag
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./area/postgres/dataset/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432